name: Get Latest CheckMK Version
on:
  workflow_call:
    inputs:
      version:
        type: string
        required: true
    outputs:
      latest-version: ${{ jobs.get-latest-version.outputs.latest-version }}
jobs:
  get-latest-version:
    runs-on: ubuntu-latest
    steps:      
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Get Latest Version
        id: get-latest-version
        run: echo "latest-version=$(./scripts/get-latest-cmk-version.py ${{ inputs.version }})" >> $GITHUB_OUTPUT