name: Test Checkmk
on:
  workflow_call:
    inputs: 
      artifact-name:
        type: string
        required: true
      version:
        type: string
        required: true
    outputs:
      latest-version:
        description: Latest Version for ${{ inputs.version }}
        value: ${{ jobs.get-checkmk-docker.outputs.latest-version }}
jobs:
  get-checkmk-docker:
    runs-on: ubuntu-latest
    outputs:
      latest-version: ${{ steps.get-latest-version.outputs.latest-version }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Get Latest Version
        id: get-latest-version
        run: echo "latest-version=$(./scripts/get-latest-cmk-version.py ${{ inputs.version }})" >> $GITHUB_OUTPUT