name: Get Latest CheckMK Versions
on:
  workflow_call:
    inputs:
      versions:
        type: string
        required: true
    outputs:
      versions-matrix:
        description: Versions Matrix From Versions Input
        value: ${{ jobs.output-versions-matrix.outputs.versions-matrix }}
jobs:
  output-versions-matrix:
    runs-on: ubuntu-latest
    outputs:
      versions-matrix: ${{ steps.output-versions-matrix.outputs.versions-matrix }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Output Versions Matrix
        id: output-versions-matrix
        run: echo "versions-matrix=$(./scripts/create-versions-matrix.py ${{ inputs.versions }})" >> $GITHUB_OUTPUT 
      - name: Echo Versions Matrix
        run: echo "${{ steps.output-versions-matrix.outputs.versions-matrix }}" 