name: Get Latest CheckMK Versions
on:
  workflow_call:
    inputs:
      versions:
        type: string
        required: true
    outputs:
      versions:
        description: Versions Matrix From Versions Input
        value: ${{ jobs.output-versions.outputs.versions }}
jobs:
  output-versions:
    runs-on: ubuntu-latest
    outputs:
      versions: ${{ steps.output-versions.outputs.versions }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Output Versions Matrix
        id: output-versions
        run: echo "versions=$(./scripts/create-versions-matrix.py ${{ inputs.versions }})" >> $GITHUB_OUTPUT