name: Test Checkmk
on:
  workflow_call:
    inputs: 
      artifact-name:
        type: string
        required: true
      version:
        type: string
        required: true
jobs:
  get-checkmk-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Download Checkmk
        run: wget --no-verbose https://download.checkmk.com/checkmk/${{ inputs.version }}/check-mk-raw-docker-${{ inputs.version }}.tar.gz
      - name: Create Dockerfile Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}-${{ inputs.version }}
          path: check-mk-raw-docker-${{ inputs.version }}.tar.gz
          retention-days: 1