name: Test Checkmk
on: workflow_dispatch
jobs:
  checkmk-docker-setup:
    runs-on: ubuntu-latest
    container:
      image: checkmk/check-mk-raw:2.3.0-latest
    steps:
      - name: Verify Checkmk
        run: which omd
      - name: List Files
        run: ls /opt/omd/sites