name: Test Checkmk
on: push
jobs:
  checkmk-docker-setup:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ['2.1.0', '2.2.0', '2.3.0']
    #container:
    #  image: checkmk/check-mk-raw:${{ matrix.version }}-latest
    steps:
      - name: Start Docker Container
        run: docker container run -dit -p 8080:5000 -p 8000:8000 --tmpfs /opt/omd/sites/cmk/tmp:uid=1000,gid=1000 -v monitoring:/omd/sites --name monitoring -v /etc/localtime:/etc/localtime:ro --restart always checkmk/check-mk-raw:${{ matrix.version }}-latest
      - name: List omd status
        run: docker exec monitoring sh -c "omd status"
        continue-on-error: true
      - name: Sleep 30s
        run: docker exec monitoring sh -c "sleep 30s"
        shell: bash
      - name: List omd status
        run: docker exec monitoring sh -c "omd status"
      - name: Copy Automation to Runner
        run: docker cp monitoring:/opt/omd/sites/cmk/var/check_mk/web/automation/automation.secret ./automation_secret_${{ matrix.version }}
      - name: Get Automation Secret
        uses: actions/upload-artifact@v4
        with:
          name: Automation Secret
          path: ./automation_secret_${{ matrix.version }}
      - name: List Running Container Processes
        run: docker exec monitoring sh -c "ps aux | grep -E '/usr/bin/omd create.*cmk' | head -n 1" 
      
      
      
      
      
      
      
      
      
      
      #- name: Create CheckMK Docker Container
      #  run: docker container run -dit -p 8080:5000 -p 8000:8000 --tmpfs /opt/omd/sites/cmk/tmp:uid=1000,gid=1000 -v monitoring:/omd/sites --name monitoring -v /etc/localtime:/etc/localtime:ro --restart always checkmk/check-mk-raw:2.3.0-latest
      
      #- name: List Monitoring Logs
      #  run: docker container logs monitoring
      #- name: List Container Users
       # run: docker exec monitoring sh -c "cat /etc/passwd"
      #- name: Site Status
      #  run: docker exec monitoring sh -c "omd status cmk"
      #- name: Start cmk site
      #  run: docker exec monitoring sh -c "omd start cmk"
      #- name: Create Test Site
      #  run: docker exec monitoring sh -c "omd create test"
      #- name: Output Automation
      #  id: output-automation
      #  run: docker exec monitoring sh -c 'echo "automation_secret=$(cat /opt/omd/sites/test/var/check_mk/web/automation/automation.secret)"'
      #- name: Display Secret
      #  run: echo "${{ steps.output-automation.outputs.automation_secret }}"