name: Checkmk Test
on: push
jobs:
  get-checkmk-docker:
    strategy:
      matrix:
        versions:
          - '2.1.0'
          - '2.2.0'
          - '2.3.0p36'
    uses: ./.github/workflows/get-checkmk-docker.yml
    with:
      version: ${{ matrix.versions }}
      artifact-name: madeup
  echo-latest-version:
    runs-on: ubuntu-latest
    needs: get-checkmk-docker
    steps:
      - run: echo ${{ needs.get-checkmk-docker.outputs.latest-version }}      
    