name: Checkmk Test
on: push
jobs:
  get-latest-versions:
    uses: ./.github/workflows/get-latest-versions.yml
    with:
      versions: "2.1.0,2.2.0,2.3.0"

  get-checkmk-docker:
    needs: get-latest-versions
    env:
      MATRIX: ${{ needs.get-latest-versions.outputs.versions-matrix }}
    strategy:
      matrix: ${{ fromJSON($MATRIX) }} 
    uses: ./.github/workflows/get-checkmk-docker.yml
    with:
      version: ${{ matrix.version }}
      artifact-name: checkmk-docker

  test-checkmk-connectivity:
    needs: get-checkmk-docker
    strategy:
      matrix:
        versions:
          - '2.1.0'
          #- '2.2.0'
          #- '2.3.0p22'
    uses: ./.github/workflows/test-checkmk-connectivity.yml
    with:
      version: ${{ matrix.versions }}
    
    