name: Checkmk Test
on: push
jobs:
  get-latest-versions:
    runs-on: ubuntu-latest
    env:
      versions: '2.1.0,2.2.0,2.3.0'
    outputs:
      versions: ${{ steps.output-matrix.outputs.versions }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Output Versions Matrix
        id: output-matrix
        run: echo "versions=$(./scripts/create-versions-matrix.py $versions)" >> $GITHUB_OUTPUT

  echo-matrix:
    needs: get-latest-versions
    runs-on: ubuntu-latest
    env:
      matrix: ${{ needs.get-latest-versions.outputs.matrix }}
    steps:
      - name: echo env
        run: echo "$matrix"
      - name: echo needs
        run: echo "${{ needs.get-latest-versions.outputs.matrix }}"

  get-checkmk-docker:
    needs: get-latest-versions
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        version: ${{ fromJSON(needs.get-latest-versions.outputs.matrix) }}
    steps:
      - name: Download Checkmk
        run: wget --no-verbose https://download.checkmk.com/checkmk/${{ matrix.version }}/check-mk-raw-docker-${{ matrix.version }}.tar.gz
      - name: Create Dockerfile Artifact
        uses: actions/upload-artifact@v4
        with:
          name: checkmk-docker-${{ matrix.version }}
          path: check-mk-raw-docker-${{ matrix.version }}.tar.gz
          retention-days: 1

  #get-checkmk-docker:
  #  needs: get-latest-versions
  #  strategy:
  #    matrix: "${{ fromJSON(needs.get-latest-versions.outputs.matrix) }}" 
  #  uses: ./.github/workflows/get-checkmk-docker.yml
  #  with:
  #    version: ${{ matrix.version }}
  #    artifact-name: checkmk-docker

  test-checkmk-connectivity:
    needs: get-checkmk-docker
    strategy:
      matrix:
        versions:
          - '2.1.0'
          #- '2.2.0'
          #- '2.3.0p22'
    uses: ./.github/workflows/test-checkmk-connectivity.yml
    with:
      version: ${{ matrix.versions }}
    
    