name: Checkmk Test
on: push
jobs:
  get-latest-versions:
    uses: ./.github/workflows/get-latest-versions.yml
    with:
      versions: "2.1.0,2.2.0,2.3.0"

  echo-matrix:
    needs: get-latest-versions
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.output-matrix.outputs.matrix }}
    env:
      matrix: ${{ needs.get-latest-versions.outputs.versions-matrix }}
    steps:
      - name: echo matrix
        id: output-matrix
        run: echo "matrix=$matrix" >> $GITHUB_OUTPUTS

  get-checkmk-docker:
    needs: echo-matrix #get-latest-versions
    strategy:
      matrix: "${{ fromJSON(needs.echo-matrix.outputs.matrix) }}" 
    uses: ./.github/workflows/get-checkmk-docker.yml
    with:
      version: ${{ matrix.version }}
      artifact-name: checkmk-docker

  test-checkmk-connectivity:
    needs: get-checkmk-docker
    strategy:
      matrix:
        versions:
          - '2.1.0'
          #- '2.2.0'
          #- '2.3.0p22'
    uses: ./.github/workflows/test-checkmk-connectivity.yml
    with:
      version: ${{ matrix.versions }}
    
    