name: Checkmk Test
on: push
jobs:
  get-checkmk-docker:
    strategy:
      matrix:
        versions:
          - '2.1.0'
          #- '2.2.0'
          #- '2.3.0p22'  
    uses: ./.github/workflows/get-checkmk-docker.yml
    with:
      version: ${{ matrix.versions }}
      artifact-name: checkmk-docker

  test-checkmk-connectivity:
    needs: get-checkmk-docker
    strategy:
      matrix:
        versions:
          - '2.1.0'
          #- '2.2.0'
          #- '2.3.0p22'
    uses: ./.github/workflows/test-checkmk-connectivity.yml
    with:
      version: ${{ matrix.versions }}
    
    