name: Checkmk Test
on: push
jobs:         
  get-latest-versions:
    uses: ./.github/workflows/get-latest-versions.yml
    with:
      versions: '2.1.0,2.2.0,2.3.0' 

  get-checkmk-docker:
    needs: get-latest-versions
    strategy:
      matrix: 
        version: "${{ fromJSON(needs.get-latest-versions.outputs.versions) }}" 
    uses: ./.github/workflows/get-checkmk-docker.yml
    with:
      version: ${{ matrix.version }}
      artifact-name: checkmk-docker

  test-checkmk-connectivity:
    needs:
      - get-latest-versions
      - get-checkmk-docker
    strategy:
      matrix:
        version: "${{ fromJSON(needs.get-latest-versions.outputs.versions) }}"
    uses: ./.github/workflows/test-checkmk-connectivity.yml
    with:
      version: ${{ matrix.version }}
    
    